using UnityEngine;

namespace Technie.PhysicsCreator
{
    public class HullMapping
    {
        public MeshCollider[] autoGeneratedColliders;

        public Collider generatedCollider;
        public Hull sourceHull;

        public HullPainterChild[] targetAutoGeneratedChilds;

        public HullPainterChild targetChild;

        public void AddAutoChild(HullPainterChild newChild, MeshCollider newCollider)
        {
        }
    }
}